In [3]:
# 1. Create a 1D NumPy array of 10 elements and find its mean, median, and standard deviation.
arr = np.array([10,20,30,40,50])
print("Mean:",np.mean(arr))
print("Median:",np.median(arr))
print("Standard:",np.std(arr))

Mean: 30.0
Median: 30.0
Standard: 14.142135623730951


In [4]:
# 2. Generate a 3x3 identity matrix and multiply it with another 3x3 random integer matrix.
eye = np.eye(3) 
print("\nIndentity Matrix:\n", eye)


Indentity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# 3. Create a 2D array of shape (4,4) with values from 1 to 16 and extract the 2nd and 3rd columns
arr = np.arange(1,17).reshape(4,4)
columns =("4x4 array:", arr)
print("2nd and 3rd columns:", columns)

2nd and 3rd columns: ('4x4 array:', array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]]))


In [6]:
# 4. Create two arrays and perform element-wise addition, subtraction, and multiplication.
a = np.array([1,2,3])
b = np.array([4,5,6])

print("\nAddition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]


In [7]:
# 5. Generate a 1D array from 0 to 50 with a step of 5, then reshape it into a 2x5 matrix.
arr = np.arange(0,50,5)
print(arr.reshape(2,5))

[[ 0  5 10 15 20]
 [25 30 35 40 45]]


In [8]:
import numpy as np

In [9]:
# 6. Create a random 3x3 matrix, find its transpose, determinant, and inverse.
import numpy as np

matrix = np.random.randint(1, 10, (3, 3))

transpose = matrix.T

determinant = np.linalg.det(matrix)

if determinant != 0:
    inverse = np.linalg.inv(matrix)
else:
    inverse = "Inverse does not exist"

print("Matrix:\n", matrix)
print("Transpose:\n", transpose)
print("Determinant:", determinant)
print("Inverse:\n", inverse)

Matrix:
 [[3 9 7]
 [3 3 2]
 [5 2 6]]
Transpose:
 [[3 3 5]
 [9 3 2]
 [7 2 6]]
Determinant: -93.00000000000003
Inverse:
 [[-0.15053763  0.43010753  0.03225806]
 [ 0.08602151  0.1827957  -0.16129032]
 [ 0.09677419 -0.41935484  0.19354839]]


In [10]:
#7. Generate a 5x5 array of random integers between 10 and 100, and filter out values greater than 50
import numpy as np

arr = np.random.randint(10, 101, (5, 5))

filtered = arr[arr > 50]

print("5x5 Array:\n", arr)
print("Values Greater Than 50:\n", filtered)

5x5 Array:
 [[ 84  80  94  33  67]
 [ 46  93  36  39  80]
 [ 54  57  25  21  35]
 [ 33  89 100  33  43]
 [ 15  55  70  54  69]]
Values Greater Than 50:
 [ 84  80  94  67  93  80  54  57  89 100  55  70  54  69]


In [11]:
#8. Create two 1D arrays and horizontally and vertically stack them using NumPy functions
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

horizontal = np.hstack((a, b))

vertical = np.vstack((a, b))

print("Horizontal Stack:", horizontal)
print("Vertical Stack:\n", vertical)

Horizontal Stack: [1 2 3 4 5 6]
Vertical Stack:
 [[1 2 3]
 [4 5 6]]


In [12]:
#9. Create an array of 10 random numbers and replace all values greater than the mean with the mean value
import numpy as np

arr = np.random.randint(1, 100, 10)

mean = np.mean(arr)

modified = np.where(arr > mean, mean, arr)

print("Original Array:", arr)
print("Mean:", mean)
print("Modified Array:", modified)

Original Array: [13 99 66 70 53 14 51 99 27 50]
Mean: 54.2
Modified Array: [13.  54.2 54.2 54.2 53.  14.  51.  54.2 27.  50. ]


In [13]:
#10. Create an array of 20 consecutive numbers and split it equally into 4 sub-arrays
import numpy as np

arr = np.arange(1, 21)

split_arrays = np.split(arr, 4)

print("Original Array:", arr)

for i, sub_array in enumerate(split_arrays, 1):
    print(f"Sub-array {i}:", sub_array)

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sub-array 1: [1 2 3 4 5]
Sub-array 2: [ 6  7  8  9 10]
Sub-array 3: [11 12 13 14 15]
Sub-array 4: [16 17 18 19 20]
