In [1]:
# Installnumpy Linrary
!pip install numpy


[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
# Importing the numpy Library
import numpy as np
print("Numpy Version:", np.__version__)

Numpy Version: 2.4.4


In [2]:
# Create a 1D array
arr1 = np.array([10,20,30,40,50])
print("1D Array:\n", arr1)

# Create a 2D aaray
arr2 = np.array([[1,2,3], [4,5,6]])
print("\n2D Array:\n", arr2)
print("\nDimensions of arr3:", arr2.ndim)

# Create a 3D array
arr3 = np.array([[[1,2], [3,4]],[[5,6],[7,8]]])
print("\n 3D Array:\n", arr3)

# Check array dimensions 
print("\n Dimensions of arr3:", arr3.ndim)

1D Array:
 [10 20 30 40 50]

2D Array:
 [[1 2 3]
 [4 5 6]]

Dimensions of arr3: 2

 3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

 Dimensions of arr3: 3


In [3]:
# Array Properties 

In [4]:
print("\nArray Shape (rows, columns):", arr2.shape)
print("Array Size (total elements):", arr2.size)
print("Array Data Type:", arr2.dtype)


Array Shape (rows, columns): (2, 3)
Array Size (total elements): 6
Array Data Type: int64


In [5]:
zeros = np.zeros((2,3))  # 2x3 matrix filled with zeros 
ones = np.ones((3,2))    # 3x2 matrix filled with ones
eye = np.eye(3)          # 3x3 indentity matrix 
rand = np.random.rand(2,3) # random values between 0 and 1
arange_arr = np.arange(0,10,2) # Even numbers from 0 to 8 
linspace_arr = np.linspace(0,1,5)  # 5 equally spced values between 0 and 1

print("\nZeros Array\n", zeros)
print("\nOnes Array:\n", ones)
print("\nIndentity Matrix:\n", eye)
print("\nRandom Array:\n", rand)
print("\nArange Array:\n", arange_arr)
print("\nLinspace Array:\n", linspace_arr)


Zeros Array
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Indentity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array:
 [[0.78745421 0.40485138 0.09325006]
 [0.69657666 0.26559548 0.62717258]]

Arange Array:
 [0 2 4 6 8]

Linspace Array:
 [0.   0.25 0.5  0.75 1.  ]


In [6]:
# Array Indexing and Slicing 

In [7]:
arr= np.array([10,20,30,40,50,60])
print("\nOriginal Array:", arr)
print("First Element:", arr[0])
print("Last Element:", arr[-1])
print("Slice [1:4]:", arr[1:4])
print("Every 2nd Element:", arr[::2])
print("Every 2nd Element:", arr[1::2])

# 2D Array slicing 
arr2d = np.array([[10,20,30], [40,50,60],[70,80,90]])
print("\n2D Array:\n", arr2d)
print("Element at [1,2]:", arr2d[1,2])
print("First two rows and first two columns:\n", arr2d[:2, :2])


Original Array: [10 20 30 40 50 60]
First Element: 10
Last Element: 60
Slice [1:4]: [20 30 40]
Every 2nd Element: [10 30 50]
Every 2nd Element: [20 40 60]

2D Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at [1,2]: 60
First two rows and first two columns:
 [[10 20]
 [40 50]]


In [8]:
# Array Operations (Element - wise)

In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("\nAddition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/ b)
print("Power:", a**2)


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Power: [1 4 9]


In [10]:
# Statistical and Mathmatical Functions

In [11]:
arr = np.array([10,20,30,40,50])

print("\nSum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Minimun:", np.min(arr))
print("Maximum:", np.max(arr))


Sum: 150
Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Minimun: 10
Maximum: 50


In [12]:
# Reshaping and Flattening Arrays

In [13]:
arr = np.arange(1,13)
print("\nOriginal 1D Array:", arr)

reshaped = arr.reshape(3,4)
print("Reshaped to 3x4 Matrix:\n", reshaped)

# reshpaed1 = arr.reshape(5,5)
#print("Reshaped to 3x4 Matrix:\n", reshaped1)

flattened = reshaped.flatten()
print("Flattened Back to 1D:", flattened)


Original 1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped to 3x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened Back to 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [14]:
# Concatenation and Stacking 

In [15]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6],[7,8]])

print("\nHorizontal Stack:\n", np.hstack((x,y)))
print("Vertical Stack:\n", np.vstack((x,y)))


Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]
Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [16]:
# Boolean Indexing and Filtering 

In [17]:
arr = np.array([5,10,15,20,25,30])
filter_arr = arr > 15
print("\nFilter Boolean Array:", filter_arr)
print("Filtered Values (arr > 15):", arr[filter_arr])


Filter Boolean Array: [False False False  True  True  True]
Filtered Values (arr > 15): [20 25 30]


In [18]:
# Random Numbers in Numpy

In [19]:
print("\nRandom Integer between 1-100:", np.random.randint(1, 100))
print("Random Float:", np.random.random())
print("Random 3x3 Matrix:\n", np.random.randint(10,50, size=(3,3)))

# print random 5x6 float matrix


Random Integer between 1-100: 60
Random Float: 0.33130812798212395
Random 3x3 Matrix:
 [[42 34 42]
 [27 36 29]
 [29 10 10]]


In [20]:
# Linear Alegebra Operations 

In [22]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])

print("\n<Matrix 1:\n", mat1)
print("Matrix 2:\n", mat2)
print("\n<Matrix Multiplication:\n", np.dot(mat1,mat2))
print("Transpose of Matrix 1:\n", mat1.T)
print("Determinant of Matrix 1:", np.linalg.det(mat1))
print("Inverse of Matrix 1:\n", np.linalg.inv(mat1))


<Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[5 6]
 [7 8]]

<Matrix Multiplication:
 [[19 22]
 [43 50]]
Transpose of Matrix 1:
 [[1 3]
 [2 4]]
Determinant of Matrix 1: -2.0000000000000004
Inverse of Matrix 1:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [23]:
# Copy vs view (memory concep)

In [24]:
original = np.array([1,2,3,4])
view_arr = original.view()
copy_arr = original.copy()

original[0] = 99

print("\nOriginal Array:", original)
print("View Array (Changes refelected):", view_arr)
print(" Copy Array (Independent):", copy_arr)


Original Array: [99  2  3  4]
View Array (Changes refelected): [99  2  3  4]
 Copy Array (Independent): [1 2 3 4]
